<?php

/**
 * Implements hook_menu().
 */
function spy_glass_menu() {
  $items = array();
  $items['node/%node/spy_glass'] = array(
    'title' => 'Spy Glass',
    'description' => 'Take a close look',
    'page callback' => 'spy_glass_page',
    'page arguments' => array(1),
    'access callback' => 'node_access',
    'access arguments' => array('view', 1),
    'type' => MENU_LOCAL_TASK,
  );

  return $items;
}

function spy_glass_page($node) {
  $information = _spy_glass_serious_spying_business($node);
  $content = array();
  foreach ($information as $item) {
    $content[] = array(
      '#type' => 'markup',
      '#markup' => theme('spy_glass_item', $item),
    );
  }
  return $content;
}
/**
 * Implement hook_theme()
 */
function spy_glass_theme() {
  return array(
    'spy_glass_item' => array(
      'arguments' => array('title' => NULL, 'data' => NULL),
      'template' => 'spy-glass-item',
    ),

/*    // this is for theme_spy_glass_item
    'spy_glass_item' => array(
      'variables' => array('item' => NULL),
    ),*/
  );
}

/*function theme_spy_glass_item($variables){
  $output = '<div class="output-from-spy">';
  $output .= '<strong>' . check_plain($variables['title']) . '</strong><br />';
  $output .= '<em>' .  check_plain($variables['data']) . '</em>';
  $output .= '</div>';

  return $output;
}*/

/**
 * Implements hook_preprocess().
 */
function spy_glass_preprocess_spy_glass_item (&$variables) {

  $variables['title'] = check_plain($variables['title']);
  $variables['data'] = check_plain($variables['data']);
  $variables['module_name'] = 'Spy Glass';
}

/**
 * Collecting some super secret information about this node.
 */
function _spy_glass_serious_spying_business($node) {
  $information = array();
  $information[] = array(
    'title' => t('Title Character Count'),
    'data' => t('There are @num characters in the $node->title.', array('@num' => strlen($node->title))),
  );
  $seconds = $node->changed - $node->created;
  $information[] = array(
    'title' => t('Timestamp Differences'),
    'data' => t('The $node->changed timestamp is @seconds seconds different from the $node->created timestamp.', array('@seconds' => $seconds)),
  );
  if ($node->translate == 0) {
    $information[] = array(
      'title' => t('Translated?'),
      'data' => t('This node is NOT translated into pirate speak, hope you know English.'),
    );
  }
  $information[] = array(
    'title' => t('Hash'),
    'data' => md5($node->title),
  );
  // Example of potential user input data that needs to be sanitized.
  // Instead of hard-coding this, it could be getting loaded from the db
  // where a user has entered the info.
  $information[] = array(
    'title' => t('Nefarious data'),
    'data' => '<a href="#" onclick="alert(\'GOTCHA !!!\'); return false;">click me</a>',
  );
  return $information;
}