<?php

function form_fun_menu() {
  $items = array();

  //Cake or pie
  $items['admin/form-fun'] = array(
    'title' => 'Form Fun',
    'page callback' => 'form_fun_page',
    'access arguments' => array('access content'),
    'file' => 'form_fun.cake.inc',
    'type' => MENU_NORMAL_ITEM,
    'weight' => -15,
  );

  // with "#tree" parameter
  $items['admin/form-fun/tree'] = array(
    'title' => 'I am lost',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('form_fun_tree'),
    'access arguments' => array('access content'),
    'file' => 'form_fun.tree.inc',
    'type' => MENU_NORMAL_ITEM,
    'weight' => 1,
  );

  // demonstration of form states
  $items['admin/form-fun/states'] = array(
    'title' => 'FORM STATES',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('form_fun_states'),
    'access arguments' => array('access content'),
    'file' => 'form_fun.states.inc',
    'type' => MENU_NORMAL_ITEM,
    'weight' => 2,
  );



  return $items;
}