<?php

/**
 * Implements hook_menu().
 */
function menu_magic_menu() {
  $items = array();

    // this function is at the bottom of this page
    $items['magic'] = array(
      'title' => 'A little Magic',
      'page callback' => 'menu_magic_basic',
      'access arguments' => array('access content'),
    );

  $items['magic/%'] = array(
    'title' => 'Holly Magic',
    'page callback' => 'menu_magic_extra',
    'page arguments' => array(1),
    'access arguments' => array('access content'),
    'file' => 'menu_magic.extra.inc',
  );


  $items['user/%/magic'] = array(
    'title' => 'USER Magic',
    'description'=> 'Magic for the user',
    'page callback' => 'menu_magic_user_tab',
    'page arguments' => array(1, 2),
    'access arguments' => array('access content'),
    'file' => 'menu_magic.user.inc',
    'type' => MENU_LOCAL_TASK,
  );


  //put % as wildcard into 'node/%/magic', but better use %node for autoload option
  $items['node/%node/magic'] = array(
    'title' => 'Node Magic',
    'description'=> 'Magic for the NODE',
    'page callback' => 'menu_magic_node_context',
    'page arguments' => array(1),
    'access arguments' => array('access content'),
    'file' => 'menu_magic.context.inc',
    'type' => MENU_LOCAL_TASK,
    'context' => MENU_CONTEXT_PAGE | MENU_CONTEXT_INLINE,
  );

  //
  return $items;
}

// puts it into navigation menu by default
function menu_magic_basic() {
  $content = array();
  $content['raw_markup'] = array(
    '#type' => 'markup',
    '#markup' => 'THIS IS TRULY MAGICAL STUFF ',
    '#prefix' => '<div class="my-basic">',
    '#suffix' => '</div>',
  );

  $variables = array(
    'path' => 'http://placekitten.com/440/440',
    'alt' => t('This kitty is super'),
    'title' => t('This is cute title'),
  );

  $content['themed_data'] = array(
    '#type' => 'markup',
    '#markup' => theme('image', $variables),
    '#prefix' => '<div id="img-wrap">',
    '#suffix' => '</div>',
    '#attached' => array(
      'css' => array(
        drupal_get_path('module', 'menu_magic') . '/menu_magic.css',
      ),
    ),
  );

  $content['renderable_element'] = array(
    '#theme' => 'item_list',
    '#title' => t('How do we do what this is?'),
    '#items' => array(
      t('Wass ist Dass'),
      t('Does it smell'),
      t('Do they fly'),
      t('The current time is %time ', array('%time' => date('r'))),
    ),
    '#attributes' => array(
      'class' => 'my-item-list not-your-list',
    ),
    '#cache' => array(
      'keys' => array('menu_magic', 'renderable_element'), // menu_magic:renderable_element
      'bin' => 'cache',
      'expire' => time() + 30,
      'granularity' => DRUPAL_CACHE_PER_PAGE,
    ),
  );


  return $content;
}