<?php


/**
 * hook_permission()
 */

function demo_permission() {
  return array(
    'administer demo module' => array(
      'title' => t('Administer DEMO module'),
      'description' => t('Perform administration tasks for DEMO module.'),
    ),
  );
}
/**
 * Implement hook_node_view()
 */
function demo_node_view($node, $view_mode, $langcode) {

  if ($node->type == 'blog') { //show on blog posts only

  $node->content['css_field'] = array(
    '#type' => 'markup',
    '#markup' => '<p>' . t("THIS IS ONLY A DEMO FIELD.") . '</p>',
    '#weight' => -10,
  );
    $node->content['demo_list'] = array(
      '#items' => array('green', 'blue', 'red', 'yellow'),
      '#theme' => 'item_list',
      '#weight' => -20,
    );

  }


/*  $node->content['css_field'] = array(
    '#markup' => $additional_field,
    '#weight' => 10,
    '#theme' => 'druzen_css_field',
  );*/


  //krumo($node);

}